# Generated by Django 5.2.17 on 2026-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percepcao', models.CharField(choices=[('muito_bem', 'Muito bem'), ('bem', 'Bem'), ('neutro', 'Neutro'), ('preocupado', 'Preocupado'), ('sobrecarregado', 'Sobrecarregado')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
